version: '3.8'

services:
  bookingclone.api:
    container_name: BookingClone_API
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDevelopment
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "13001:80"
      #- "13000:443"
    #volumes:
    #  - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  sql-server:
    container_name: sql_server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=abcde12345$
    ports:
      - 1433:1433
    restart: unless-stopped
      
  azurite:
    container_name: Azurite
    restart: unless-stopped
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002